### ISSUE TITLE
add support for grunt 1.0.0

### ISSUE THREAD

**Issue by sagiegurari** [pimterry/grunt-coveralls#16]
since the peer dependency is of >=0.4.0, new grunt version (1.x.x) is not supported.
Can you please update the needed?

**Comment by sagiegurari** [comment]
now that I look at it, it is ok already.
The issue is that you didn't publish that change to npm.
So you just need to npm publish and that's it.

**Comment by pimterry** [comment]
You're totally right, not sure how I missed that (and sorry for the delay too!). I've now published the new version. Let me know if you have any trouble.

**Comment by sagiegurari** [comment]
thanks
