### ISSUE TITLE
Security issue: Prototype pollution attack(Introduced by the coveralls@2.13.3 => request@2.79.0 => hawk@3.1.3 => hoek@2.16.3) 

### ISSUE THREAD

**Issue by MichaelTsengLZ** [pimterry/grunt-coveralls#18]
The latest version grunt-coveralls@1.0.1 uses coveralls@^2.11.1. However, coveralls@^2.11.1 has a vulnerability which is introduced by hoek@2.16.3. More information is here:

https://nodesecurity.io/advisories/566
https://snyk.io/vuln/npm:hoek:20180212

Could you please update coveralls to the latest version to solve the vulnerability? Thank you so much.

**Comment by pimterry** [comment]
Thanks for the report! Fixed in 2.0.0.
